### ISSUE TITLE
After performing a stop operation, the next playback operation fails.

### ISSUE THREAD

**Issue by torakiti2017** [reckhou/MidiBard2#19]
When I press the stop button (■) with a song selected, the song does not play even if I press the play button (▶).
1. Select a song (double-click)
2. press the stop button
3. press the Play button
4.The song does not play.

Double-clicking the song again makes the playback button work.
I updated to V2.0.0.3 and this situation occurred.
I am sorry if this is my mistake. (Settings, etc.)

Thanks for updating MidiBard.

**Comment by reckhou** [comment]
You need to select the song again once you pressed the stop button.
